# NOMBRE DE LA APLICACIÓN
spring.application.name=pancubarber

# CONFIGURACIÓN DE LA BASE DE DATOS (H2)
# Usamos un archivo local para que las citas no se borren al reiniciar
spring.datasource.url=jdbc:h2:file:./data/pancudb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ESTRATEGIA DE ACTUALIZACIÓN
# 'update' crea las tablas si no existen y mantiene los datos
spring.jpa.hibernate.ddl-auto=update

# CONSOLA H2 (Para que podás revisar los datos desde el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CONFIGURACIÓN DE THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# PUERTO (Render asignará uno automáticamente, pero dejamos el 8080 por defecto)
server.port=8080